version: "3.8"

services:
  postgres-trabalhodw3:
    container_name: postgres
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=trabalhodw3
      - POSTGRES_DB=trabalhodw3
    ports:
      - '5433:5432'
    volumes:
      - docker-postgres:/var/lib/postgresql/data
  pgadmin-trabalhodw3:
    container_name: pgadmin
    image: dpage/pgadmin4:6.12
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
volumes:
  docker-postgres: { }
